name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_REDIS_URL: ${{ secrets.REDIS_URL }}
          envkey_SOCKET_PROTECT_TOKEN: ${{ secrets.SOCKET_PROTECT_TOKEN }}
          file_name: .env
          fail_on_empty: false

      - name: Build Docker images
        run: |
          docker compose build --force-rm --no-cache

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: Run Docker images
        run: |
          docker compose up -d --force-recreate --remove-orphans
